### PR TITLE
Configurable LB policy

### PR DESCRIPTION
**Pull request by kwarunek**
If this is ok I will provide PR to disthene writer

### CODE REVIEW

**Comment by EinsamHauer** [comment]
Hi Krzysztof, 

The patch itself looks just fine. Before merging could you please share the use case for policies other than *tokenDcAwareRoundRobinPolicy*?

Thanks, Andrei.

**Comment by kwarunek** [comment]
Hi,

Actually we're interested in LatencyAwarePolicy only. The rationale:

1. compaction process can be I/O intensive
2. replace/repair/rebalance of node are I/O, CPU intensive (we're investigating this, since C* should mark that node)
3. our C* setup is vm based. The hosts have "dynamic" workload, that sometimes affects our nodes
4. increase reliability in case of hardware failure (eg. disk and then raid degradation)
5. favouritism DC means that you have primary DC (which isn't bad by itself), but it doesn't makes such a sense in more distributed setups... ..actually the LatencyAwarePolicy should choose the same nodes as DC-aware

**Comment by EinsamHauer** [comment]
That makes sense. 

On the other hand the whole disthene-reader concept (in what conerns C*) is built around token awareness. And I don't see much point in using token unaware balancing - requests will hit replicas anyhow, but with token unaware policy there will be extra load on coordinator nodes (i.e. lowest latency nodes).

So, AFAIU in general case with 
`LatencyAwarePolicy.builder(new RoundRobinPolicy()).build()`
any request will hit the lowest latency coordinator node and then it will hit the replica anyhow. Looks like just extra load on this coordinator without any benefit to the node actually containing data. 

Probably it makes sense to wrap this latency aware policy in `TokenAwarePolicy` ?

**Comment by kwarunek** [comment]
I will run test with `TokenAwarePolicy(Latency....)`, but it sounds good.

**Comment by EinsamHauer** [comment]
Looks good to me! I will merge and double check/test over the weekend.

**Pull request merged**
